site_name: ParaViewGeophysics
pages:
    - Home: index.md
    - What's Next: What's-Next.md
    - Getting Started: How-to-Use-This-Wiki.md
        - Using: Using-Outside-Python-Modules.md
theme: readthedocs
