site_name: ParaViewGeophysics
site_author: Bane Sullivan
site_description: "Documentation for the ParaViewGeophysics repository."
repo_url: https://github.com/banesullivan/ParaViewGeophysics
#repo_name: PVGP on GitHub
site_url: https://banesullivan.github.io/ParaViewGeophysics/

theme_dir: cinder

markdown_extensions:
    - smarty
    - toc
    - pymdownx.tasklist:
        custom_checkbox: true

plugins:
    - search

pages:
- Home: index.md

- Getting Started: Getting-Started.md

- Plugins:
    - About ParaView Plugins: Plugins/Plugins.md
    - Build Your Own Plugins: Plugins/Build-Your-Own-Plugins.md
    - Readers:
        - Read SGeMS Grid: Plugins/Readers/Read-SGeMS-Grid.md
        - Read GSLIB File: Plugins/Readers/Read-GSLIB-File-to-Table.md
        - Read UBC Mesh Two File FormatRe: Plugins/Readers/Read-UBC-Mesh-Two-File-Format.md
        - Read Binary Packed Data: Plugins/Readers/Read-Binary-Packed-Data-to-Table.md
        - Read Delimited File: Plugins/Readers/Read-Delimited-File-to-Table.md
    - Filters:
        - Table to Uniform Grid: Plugins/Filters/Table-to-Uniform-Grid.md
        - Flip Grid Axii: Plugins/Filters/Flip-Grid-Axii.md
        - Reshape Table: Plugins/Filters/Reshape-Table.md
        - Add Cell Connectivity to Points: Plugins/Filters/Add-Cell-Connectivity-to-Points.md
        - Points to Tube: Plugins/Filters/Points-to-Tube.md
        - Translate Origin of Grid: Plugins/Filters/Translate-Origin-of-Grid.md
        - Normalize Array: Plugins/Filters/Normalize-Array.md

- PVGPpy:
    - About PVGPpy: PVGPpy/About-PVGPpy.md
    - Export Sub-Module:
        - Export as VTKjs: PVGPpy/export/exportVTKjs.md
    - Vis Sub-Module:
        - Clip Through: PVGPpy/vis/Clip-Through.md
        - Many Slices Along Points: PVGPpy/vis/Many-Slices-Along-Points.md

- Resources:
    - Exporting Visualizations: Examples/Exporting-Visualizations.md
    - Scripts:
        - Example Script: Scripts/Example-Script.md
    - Examples/Tutorials:
        - Slice Model Along PolyLine: Examples/Slice-Model-Along-PolyLine.md
    - Virtual Reality:
        - Entering Virtual Reality: Virtual-Reality/Entering-Virtual-Reality.md
