site_name: ParaViewGeophysics
site_author: Bane Sullivan

repo_url: https://github.com/banesullivan/ParaViewGeophysics

theme_dir: readthedocshm

markdown_extensions:
    - smarty
    - toc

plugins:
    - search

pages:
- Home: README.md
- What's Next: What's-Next.md

- Getting Started:
    - How to Use The Docs: Getting-Started/How-to-Use-The-Docs.md
    - ParaView and VTK: Getting-Started/ParaView-and-VTK.md
    - Install These Plugins: Getting-Started/Install-Plugins.md
    - Using 3rd Party Py Libraries: Getting-Started/Using-Outside-Python-Modules.md


- Plugins:
    - About ParaView Plugins: Plugins/Plugins.md
    - Build Your Own Plugins: Plugins/Build-Your-Own-Plugins.md
    - Readers:
        - Read SGeMS Grid: Plugins/Readers/Read-SGeMS-Grid.md
        - Read GSLIB File: Plugins/Readers/Read-GSLIB-File-to-Table.md
        - Read UBC Mesh Two File FormatRe: Plugins/Readers/Read-UBC-Mesh-Two-File-Format.md
        - Read Binary Packed Data: Plugins/Readers/Read-Binary-Packed-Data-to-Table.md
        - Read Delimited File: Plugins/Readers/Read-Delimited-File-to-Table.md


- Macros:
    - Using ParaView Macros: Macros/Using-PV-Macros.md
    - Advice For Making Macros: Macros/Advice-For-Making-Macros.md
    - Scene Export Macros: Macros/Scene-Export-Macros.md
    - Our Macros:
        - Slice Model Along PolyLine: Macros/ours/Slice-Model-Along-PolyLine.md

- Virtual Reality:
    - Exporting Visualizations: Exporting-Visualizations.md
    - Entering Virtual Reality: Virtual-Reality/Entering-Virtual-Reality.md
