site_name: ParaViewGeophysics
site_author: Bane Sullivan

repo_url: https://github.com/banesullivan/ParaViewGeophysics

theme: mkdocs

markdown_extensions:
    - smarty
    - toc

pages:
- Home: index.md
- What's Next: What's-Next.md

- Getting Started:
    - How to Use The Docs: Getting-Started/How-to-Use-The-Docs.md
    - ParaView and VTK: Getting-Started/ParaView-and-VTK.md
    - Install These Plugins: Getting-Started/Install-Plugins.md
    - Using 3rd Party Py Libraries: Getting-Started/Using-Outside-Python-Modules.md

- Plugins:
    - About ParaView Plugins: Plugins/Plugins.md
    - Build Your Own Plugins: Plugins/Build-Your-Own-Plugins.md

    - Read SGeMS Grid: Plugins/Readers/Read-SGeMS-Grid.md
    - Read GSLIB File: Plugins/Readers/Read-GSLIB-File-to-Table.md
    - Read UBC Mesh Two File FormatRe: Plugins/Readers/Read-UBC-Mesh-Two-File-Format.md
    - Read Binary Packed Data: Plugins/Readers/Read-Binary-Packed-Data-to-Table.md
    - Read Delimited File: Plugins/Readers/Read-Delimited-File-to-Table.md

    - Table to Uniform Grid: Plugins/Filters/Table-to-Uniform-Grid.md
    - Flip Grid Axii: Plugins/Filters/Flip-Grid-Axii.md
    - Reshape Table: Plugins/Filters/Reshape-Table.md
    - Add Cell Connectivity to Points: Plugins/Filters/Add-Cell-Connectivity-to-Points.md
    - Points to Tube: Plugins/Filters/Points-to-Tube.md
    - Translate Origin of Grid: Plugins/Filters/Translate-Origin-of-Grid.md
    - Normalize Array: Plugins/Filters/Normalize-Array.md

- PVGPpy and Macros:
    - About PVGPpy: PVGPpy/About-PVGPpy.md
    - Using ParaView Macros: Macros/Using-PV-Macros.md
    - Advice For Making Macros: Macros/Advice-For-Making-Macros.md
    - Screenshot Macros: Macros/Screenshot-Macros.md

    - Export as VTKjs: PVGPpy/export/exportVTKjs.md

    - Clip Through: PVGPpy/macros/Clip-Through.md
    - Many Slices Along Points: PVGPpy/macros/Many-Slices-Along-Points.md

- Resources:
    - Exporting Visualizations: Examples/Exporting-Visualizations.md
    - Slice Model Along PolyLine: Examples/Slice-Model-Along-PolyLine.md
    - Entering Virtual Reality: Virtual-Reality/Entering-Virtual-Reality.md
