site_name: ParaViewGeophysics
pages:
- Home: index.md
- What's Next: What's-Next.md
- Contents: Contents.md
- Getting Started:
    - How to Use This Wiki: Getting-Started/How-to-Use-This-Wiki.md
    - ParaView and VTK: Getting-Started/ParaView-and-VTK.md
    - Install These Plugins: Getting-Started/Install-Plugins.md
    - Using 3rd Party Py Libraries: Getting-Started/Using-Outside-Python-Modules.md
- Plugins:
    - About ParaView Plugins: Plugins/Plugins.md
theme: readthedocs
